name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: "auto"

      - name: Run ruff lint
        run: uvx ruff check .

      - name: Run ruff format check
        run: uvx ruff format --check .

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: "auto"

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Run tests with coverage
        run: |
          uv run pytest \
            --cov \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage.${{ matrix.python-version }}.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.${{ matrix.python-version }}.xml
          flags: py${{ matrix.python-version }}
          name: py${{ matrix.python-version }}
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
